version: "2"
services:
    myappdocker:
        build: .
        ports:
          - "9036:9036"
        environment: 
          - MONGO_URL=mongodb
        depends_on:
          - mongodb
    mongodb: 
      container_name: my-mongodb
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootadmin
        MONGO_INITDB_DATABASE: dockerdb
      ports:
        - "27017:27017"
      volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
